# Generated by Django 6.0.4 on 2026-08-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('CASHIER', 'Кассир')], default='CASHIER', max_length=20, verbose_name='Роль'),
        ),
    ]
