# Generated by Django 6.0.4 on 2026-08-26 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SALE', 'Продажа'), ('REFUND', 'Возврат'), ('STOCK_IN', 'Поступление на склад'), ('STOCK_OUT', 'Списание со склада'), ('STOCK_ADJUST', 'Корректировка склада'), ('PRODUCT_CREATE', 'Создание товара'), ('PRODUCT_UPDATE', 'Изменение товара'), ('USER_ACTION', 'Действие пользователя')], max_length=30, verbose_name='Тип действия')),
                ('description', models.TextField(verbose_name='Описание действия')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита (Audit Log)',
                'ordering': ['-created_at'],
            },
        ),
    ]
