# Generated by Django 6.0.4 on 2026-08-26 14:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Бренд')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('icon', models.CharField(default='fa-tags', help_text='FontAwesome иконка', max_length=50, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Приход / Поступление'), ('OUT', 'Списание / Потеря'), ('ADJUSTMENT', 'Корректировка инвентаризации'), ('SALE', 'Продажа'), ('RETURN', 'Возврат от покупателя')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Себестоимость (₸)')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Движение товара',
                'verbose_name_plural': 'Движение товаров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Артикул')),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Штрихкод')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Закупочная цена (₸)')),
                ('retail_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Розничная цена (₸)')),
                ('unit', models.CharField(choices=[('шт', 'штук (шт)'), ('л', 'литров (л)'), ('мл', 'миллилитров (мл)'), ('кг', 'килограмм (кг)'), ('компл', 'комплект (компл)')], default='шт', max_length=20, verbose_name='Единица измерения')),
                ('stock_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Остаток на складе')),
                ('min_stock_alert', models.DecimalField(decimal_places=3, default=Decimal('5.000'), max_digits=12, verbose_name='Минимальный остаток (Сигнал)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
