# Generated by Django 4.2.30 on 2026-09-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_barcode_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='client_sync_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='UUID синхронизации'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Приход / Поступление'), ('OUT', 'Списание / Потеря'), ('TRANSFER_TO_SHOP', 'Отгрузка в магазин'), ('ADJUSTMENT', 'Корректировка инвентаризации'), ('SALE', 'Продажа'), ('RETURN', 'Возврат от покупателя')], max_length=20, verbose_name='Тип операции'),
        ),
    ]
