# Generated by Django 6.0.4 on 2026-08-26 14:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Номер чека')),
                ('status', models.CharField(choices=[('COMPLETED', 'Проведен (Оплачен)'), ('REFUNDED', 'Возвращен'), ('CANCELLED', 'Отменен')], default='COMPLETED', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Банковская карта'), ('TRANSFER', 'Перевод (Kaspi / QR)'), ('MIXED', 'Смешанная оплата')], default='CASH', max_length=20, verbose_name='Способ оплаты')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма без скидки (₸)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Скидка (₸)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итого к оплате (₸)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Внесено (₸)')),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сдача (₸)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Продажа (Чек)',
                'verbose_name_plural': 'Продажи (Чеки)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('purchase_price_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Закупочная цена (₸)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Розница за ед. (₸)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Скидка на позицию (₸)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итого за позицию (₸)')),
            ],
            options={
                'verbose_name': 'Позиция чека',
                'verbose_name_plural': 'Позиции чека',
            },
        ),
    ]
