# Generated by Django 6.0.4 on 2026-08-26 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='refund_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина возврата'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время возврата'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_processed', to=settings.AUTH_USER_MODEL, verbose_name='Провел возврат'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта'), ('TRANSFER', 'Kaspi QR'), ('MIXED', 'Смешанная')], default='CASH', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
