# Generated by Django 4.2.30 on 2026-08-30 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_saleorder_refund_reason_saleorder_refunded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Кассир'),
        ),
    ]
