# Generated by Django 5.2.17 on 2026-09-05 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_stockmovement_client_sync_id_and_more'),
        ('sales', '0004_alter_saleorder_cashier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='catalog.product', verbose_name='Товар'),
        ),
    ]
