# Generated by Django 5.2.17 on 2026-09-12 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_lock(apps, schema_editor):
    apps.get_model('sales', 'FinancialLock').objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_saleorderitem_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(seed_lock, migrations.RunPython.noop),
        migrations.CreateModel(
            name='OperationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(max_length=16)),
                ('fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.saleorder')),
            ],
        ),
    ]
