# Generated by Django 5.2.17 on 2026-09-24 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_financial_operation_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderitem',
            name='brand_name_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='sku_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='unit_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_bin', models.CharField(max_length=12)),
                ('buyer_address', models.CharField(max_length=500)),
                ('contract', models.CharField(blank=True, max_length=255)),
                ('seller', models.JSONField(default=dict)),
                ('lines', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта'), ('TRANSFER', 'Kaspi QR')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.saleorder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'method'), name='sale_payment_unique_method'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='sale_payment_nonnegative'), models.CheckConstraint(condition=models.Q(('method__in', ['CASH', 'CARD', 'TRANSFER'])), name='sale_payment_method_valid')],
            },
        ),
    ]
