# Generated by Django 4.2.30 on 2026-09-28 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cashshift'),
        ('sales', '0009_saleorder_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='refund_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_orders', to='users.cashshift', verbose_name='Смена возврата'),
        ),
    ]
