# Generated by Django 4.2.30 on 2026-10-08 09:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0010_saleorder_refund_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code_last4', models.CharField(max_length=4)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('activation_payment_method', models.CharField(blank=True, choices=[('CASH', 'Наличные'), ('CARD', 'Карта'), ('TRANSFER', 'Kaspi QR')], max_length=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ACTIVATE', 'Активация'), ('REDEEM', 'Оплата'), ('REFUND', 'Возврат')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='salepayment',
            name='sale_payment_method_valid',
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта'), ('TRANSFER', 'Kaspi QR'), ('GIFT', 'Сертификат'), ('MIXED', 'Смешанная')], default='CASH', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта'), ('TRANSFER', 'Kaspi QR'), ('GIFT', 'Сертификат')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='salepayment',
            constraint=models.CheckConstraint(check=models.Q(('method__in', ['CASH', 'CARD', 'TRANSFER', 'GIFT'])), name='sale_payment_method_valid'),
        ),
        migrations.AddField(
            model_name='giftcardevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftcardevent',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='sales.giftcard'),
        ),
        migrations.AddField(
            model_name='giftcardevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_events', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='giftcardevent',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order', 'kind'), name='gift_event_unique_order_kind'),
        ),
        migrations.AddConstraint(
            model_name='giftcardevent',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='gift_event_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.CheckConstraint(check=models.Q(('nominal__gt', 0)), name='gift_card_nominal_positive'),
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='gift_card_balance_nonnegative'),
        ),
    ]
