# Generated by Django 4.2.30 on 2026-10-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_giftcard_giftcardevent_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.CheckConstraint(check=models.Q(('balance__lte', models.F('nominal'))), name='gift_card_balance_not_above_nominal'),
        ),
    ]
